from enum import Enum


class WidgetKey(Enum):
    DETECTOR_SELECTOR_KEY = '-DETECTOR-'
    FLASH_TOP_NOTICE_KEY = '-FLASH-TOP-NOTICE-'
    MEDIA_SELECTOR_KEY = '-MEDIA-FILENAME-LIST-'
    MEDIA_SELECTOR_CONTAINER_KEY = '-MEDIA-FILENAMES-CONTAINER-'
    OUTPUT_FILENAME_INPUT_KEY = '-NAME-'
    SEGMENT_LIST_TABLE_KEY = '-SEGMENTS-LIST-'
    SEGMENT_TIMELINE_KEY = '-SEGMENTS-TIMELINE-'
    SKIP_BACKUP_CHECKBOX_KEY = '-SKIP-BACKUP-'
    TIMELINE_SLIDER_KEY = '-TIMELINE-'
    TOGGLE_MEDIA_SELECTOR_VISIBILITY_KEY = '-TOGGLE-MEDIA-SELECTOR-VISIBILITY-'
    VIDEO_CONTAINER_KEY = '-VIDEO-FRAME-'
    VIDEO_DURATION_LABEL_KEY = '-VIDEO-DURATION-'
    VIDEO_OUT_KEY = '-VID-OUT-'
    VIDEO_POSITION_LABEL_KEY = '-VIDEO-POSITION-'


class WidgetEvent(Enum):
    APPLICATION_LOADED_EVENT = '-APPLICATION-LOADED-'
    CONFIGURE_EVENT = '-CONFIGURE-'
    GOTO_SELECTED_SEGMENT_EVENT = 'goto_selected_segment'
    MEDIA_SELECTOR_UPDATED_EVENT = WidgetKey.MEDIA_SELECTOR_KEY.value
    PREFILL_NAME_EVENT = '-PREFILL-NAME-'
    SEGMENT_ADD_EVENT = 'Add segment'
    SEGMENT_DELETE_EVENT = 'Delete segment(s)'
    SEGMENT_IMPORTED_EVENT = '-SEGMENTS-IMPORTED-'
    SEGMENT_LIST_UPDATED_EVENT = WidgetKey.SEGMENT_LIST_TABLE_KEY.value
    SEGMENT_MERGE_EVENT = 'Merge segments'
    SEGMENT_SET_START_EVENT = 'Set start'
    SEGMENT_SET_END_EVENT = 'Set end'
    SEGMENT_TIMELINE_SELECTED_EVENT = '-SEGMENT-TIMELINE-SELECTED-'
    SEGMENT_TIMELINE_UPDATED_EVENT = WidgetKey.SEGMENT_TIMELINE_KEY.value
    SEGMENTS_VALIDATED_EVENT = 'Validate'
    SEGMENTS_SAVED_EVENT = '-SEGMENTS-SAVED-'
    SEGMENTS_UPDATED_EVENT = '-SEGMENTS-UPDATED-'
    SELECTED_DETECTOR_UPDATED_EVENT = WidgetKey.DETECTOR_SELECTOR_KEY.value
    SET_RELATIVE_POSITION_EVENT = 'set_relative_position'
    TASK_DONE_EVENT = '-TASK-DONE-'
    TIMELINE_POSTION_UPDATED_EVENT = WidgetKey.TIMELINE_SLIDER_KEY.value
    TOGGLE_MEDIA_SELECTOR_VISIBILITY_EVENT = WidgetKey.TOGGLE_MEDIA_SELECTOR_VISIBILITY_KEY.value
    VIDEO_LOADED_EVENT = '-VIDEO-LOADED-'
    VIDEO_POSITION_UPDATED_EVENT = '-VIDEO-NEW-POSITION-'
    VIDEO_NEW_FRAME_EVENT = '-VIDEO-NEW-FRAME-'
