from .keys import (
    DETECTOR_SELECTOR_KEY,
    MEDIA_SELECTOR_KEY,
    SEGMENT_LIST_TABLE_KEY,
    SEGMENT_TIMELINE_KEY,
    TIMELINE_SLIDER_KEY,
    TOGGLE_MEDIA_SELECTOR_VISIBILITY_KEY
)

APPLICATION_LOADED_EVENT = '-APPLICATION-LOADED-'
CONFIGURE_EVENT = '-CONFIGURE-'
MEDIA_SELECTOR_UPDATED_EVENT = MEDIA_SELECTOR_KEY
PREFILL_NAME_EVENT = '-PREFILL-NAME-'
SEGMENT_ADD_EVENT = 'Add segment'
SEGMENT_DELETE_EVENT = 'Delete segment(s)'
SEGMENT_IMPORTED_EVENT = '-SEGMENTS-IMPORTED-'
SEGMENT_LIST_UPDATED_EVENT = SEGMENT_LIST_TABLE_KEY
SEGMENT_MERGE_EVENT = 'Merge segments'
SEGMENT_SET_START_EVENT = 'Set start'
SEGMENT_SET_END_EVENT = 'Set end'
SEGMENT_TIMELINE_SELECTED_EVENT = '-SEGMENT-TIMELINE-SELECTED-'
SEGMENT_TIMELINE_UPDATED_EVENT = SEGMENT_TIMELINE_KEY
SEGMENTS_VALIDATED_EVENT = 'Validate'
SEGMENTS_SAVED_EVENT = '-SEGMENTS-SAVED-'
SEGMENTS_UPDATED_EVENT = '-SEGMENTS-UPDATED-'
SELECTED_DETECTOR_UPDATED_EVENT = DETECTOR_SELECTOR_KEY
TASK_DONE_EVENT = '-TASK-DONE-'
TIMELINE_POSTION_UPDATED_EVENT = TIMELINE_SLIDER_KEY
TOGGLE_MEDIA_SELECTOR_VISIBILITY_EVENT = TOGGLE_MEDIA_SELECTOR_VISIBILITY_KEY
VIDEO_LOADED_EVENT = '-VIDEO-LOADED-'
VIDEO_POSITION_UPDATED_EVENT = '-VIDEO-NEW-POSITION-'
VIDEO_NEW_FRAME_EVENT = '-VIDEO-NEW-FRAME-'
