/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Media
import org.openapitools.client.models.MediaMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param media media
 * @param duration media duration in seconds
 * @param recordingMetadata 
 */
@Serializable

data class MediaOut (

    /* media */
    @SerialName(value = "media") @Required val media: Media,

    /* media duration in seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Double,

    @SerialName(value = "recording_metadata") @Required val recordingMetadata: MediaMetadata?

)

