/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param basename Basename of recording
 * @param channel Nom de la chaine
 * @param title Program title
 * @param subTitle Program subtitle or summary
 * @param description Program description
 * @param startReal Start time stamp of recording, UNIX epoch
 * @param stopReal Stop time stamp of recording, UNIX epoch
 * @param errorMessage Error message
 * @param nbDataErrors Number of data errors during recording
 * @param recordingId Unique ID of recording
 */
@Serializable

data class MediaMetadata (

    /* Basename of recording */
    @SerialName(value = "basename") @Required val basename: kotlin.String,

    /* Nom de la chaine */
    @SerialName(value = "channel") @Required val channel: kotlin.String,

    /* Program title */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* Program subtitle or summary */
    @SerialName(value = "sub_title") @Required val subTitle: kotlin.String,

    /* Program description */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Start time stamp of recording, UNIX epoch */
    @SerialName(value = "start_real") @Required val startReal: kotlin.Int,

    /* Stop time stamp of recording, UNIX epoch */
    @SerialName(value = "stop_real") @Required val stopReal: kotlin.Int,

    /* Error message */
    @SerialName(value = "error_message") @Required val errorMessage: kotlin.String,

    /* Number of data errors during recording */
    @SerialName(value = "nb_data_errors") @Required val nbDataErrors: kotlin.Int,

    /* Unique ID of recording */
    @SerialName(value = "recording_id") @Required val recordingId: kotlin.String

) {


}

