/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param start segment start position in seconds
 * @param end segment end position in seconds
 * @param duration segment duration in seconds
 */
@Serializable

data class SegmentOutput (

    /* segment start position in seconds */
    @SerialName(value = "start") @Required val start: kotlin.Double,

    /* segment end position in seconds */
    @SerialName(value = "end") @Required val end: kotlin.Double,

    /* segment duration in seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Double

) {


}

