/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param newPosition segment position in seconds
 * @param edge edge to apply new position
 */
@Serializable

data class SegmentEditBody (

    /* segment position in seconds */
    @SerialName(value = "new_position") @Required val newPosition: kotlin.Double,

    /* edge to apply new position */
    @SerialName(value = "edge") @Required val edge: SegmentEditBody.Edge

) {

    /**
     * edge to apply new position
     *
     * Values: start,end
     */
    @Serializable
    enum class Edge(val value: kotlin.String) {
        @SerialName(value = "start") start("start"),
        @SerialName(value = "end") end("end");
    }

}

