/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Media

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlin.time.ExperimentalTime

/**
 * 
 *
 * @param id session id
 * @param createdAt 
 * @param updatedAt 
 * @param rootPath root path for medias
 * @param medias medias to process in root_path indexed by stem (filename without extension).  `imported_segments` and `segments` is empty unless you query media from `medias` or `segments` endpoints
 */
@OptIn(ExperimentalTime::class)
@Serializable

data class Session (

    /* session id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlinx.datetime.Instant,

    /* root path for medias */
    @SerialName(value = "root_path") @Required val rootPath: kotlin.String,

    /* medias to process in root_path indexed by stem (filename without extension).  `imported_segments` and `segments` is empty unless you query media from `medias` or `segments` endpoints */
    @SerialName(value = "medias") @Required val medias: kotlin.collections.Map<kotlin.String, Media>

)

