/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param edlPath Movie Pipeline EDL (Edit Decision List) file location
 */
@Serializable

data class ValidateSegmentsOut (

    /* Movie Pipeline EDL (Edit Decision List) file location */
    @SerialName(value = "edl_path") @Required val edlPath: kotlin.String

) {


}

