/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ValidationErrorLocInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param loc 
 * @param msg 
 * @param type 
 */
@Serializable

data class ValidationError (

    @SerialName(value = "loc") @Required val loc: kotlin.collections.List<ValidationErrorLocInner>,

    @SerialName(value = "msg") @Required val msg: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

