/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SegmentInput

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param title output title, must ends with .mp4
 * @param skipBackup skip backup step
 */
@Serializable
data class ValidateSegmentsBody(

    /* output title, must ends with .mp4 */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* skip backup step */
    @SerialName(value = "skip_backup") val skipBackup: kotlin.Boolean,

)

